fileDir = fileparts(which(mfilename));

inputFile = fullfile(fileDir, 'ssk.cpp');
outDir = fileDir;

mex(inputFile, ...
    '-v',...
    '-outdir', outDir, ...
    'CXXFLAGS=$CXXFLAGS -std=c++17 -Xclang -fopenmp -I/opt/homebrew/opt/libomp/include -lomp',...
    'LDFLAGS=$LDFLAGS -L/opt/homebrew/opt/libomp/lib -lomp');
